# docker-compose.yml
version: '3.9'

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_db
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=pbl5DB
  adminer:
    image: adminer
    ports:
      - 8080:8080
# version: '3'
# services:
#   web:
#     build: .
#     ports:
#       - "5000:5000"
#     restart: always
#     volumes:
#       - .:/app
