# docker-compose.yml

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_db
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=pbl5DB
  adminer:
    image: adminer
    ports:
      - 8080:8080
  flask-app:
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=development
  flask-device:
    build:
      context: ./flask-device
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development

