name: growhub
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.14
  go_router: ^14.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9  
  flutter_gen_runner: ^5.8.0

flutter_gen:
  output: lib/config/

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons-ui/
    - assets/kwiatki/
